version: '3.7'

services:
  apache:
    build: './apache'
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/public_html:/usr/local/apache2/htdocs
      - ./volumes/cert:/usr/local/apache2/cert
    depends_on:
      - php
      - devmysql
      - coldfusion

  php:
    build: './php'
    restart: always
    # Enable XDEBUG
    # Use your computer's IP address: ifconfig | ipconfig
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.1.8"
    volumes:
      - ./volumes/public_html:/usr/local/apache2/htdocs
      - ./volumes/tmp:/usr/local/tmp

  devmysql:
    build: './mysql'
    restart: always
    ports:
      - 9906:3306
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: test_db
      TZ: America/New_York
    volumes:
      - ./volumes/database:/var/lib/mysql

  coldfusion:
    build: './coldfusion'
    restart: always
    ports:
      - 8500:8500
    volumes:
      - ./volumes/public_html:/app
#     - ./volumes/coldfusion_root:/app
    env_file:
      - ./coldfusion/coldfusion.env
